# Local development configuration.
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=manualsmap
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  api:
    build: .
    restart: always
    env_file:
      - secrets-dev.env
    volumes:
      - ./:/secrets
    ports:
      - 8080:8080
